In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv("results.csv",names=["Image","Image1"])
df

Image                 Image1
0     833758612558_1846.png  441965561693_1725.png
1                         1                      1
2      357251708376_311.png   578184120957_719.png
3                         1                      1
4     278611994141_2601.png    379555453762_57.png
...                     ...                    ...
6027                      0                      1
6028  253890261988_3426.png    753932316264_69.png
6029                      1                      0
6030  988222288102_2994.png                    NaN
6031                      0                    NaN

[6032 rows x 2 columns]

In [35]:
df.insert(1,'labels',"NaN")

In [36]:
df.insert(3,'labels1',"NaN")

In [12]:
df

Image labels                 Image1 labels1
0     833758612558_1846.png    NaN  441965561693_1725.png     NaN
1                         1    NaN                      1     NaN
2      357251708376_311.png    NaN   578184120957_719.png     NaN
3                         1    NaN                      1     NaN
4     278611994141_2601.png    NaN    379555453762_57.png     NaN
...                     ...    ...                    ...     ...
6027                      0    NaN                      1     NaN
6028  253890261988_3426.png    NaN    753932316264_69.png     NaN
6029                      1    NaN                      0     NaN
6030  988222288102_2994.png    NaN                    NaN     NaN
6031                      0    NaN                    NaN     NaN

[6032 rows x 4 columns]

In [37]:
image = df['Image'].to_list()
image

['833758612558_1846.png',
 '1',
 '357251708376_311.png',
 '1',
 '278611994141_2601.png',
 '0',
 '985714726449_129.png',
 '1',
 '222887373246_1773.png',
 '1',
 '110127687078_75.png',
 '1',
 '214189042515_3281.png',
 '0',
 '683738917842_180.png',
 '1',
 '164538165078_1752.png',
 '1',
 '301001229493_1284.png',
 '1',
 '549733273277_53.png',
 '1',
 '662256656405_959.png',
 '1',
 '554448876390_107.png',
 '0',
 '674347030286_2524.png',
 '0',
 '796282255349_381.png',
 '0',
 '993023278923_62.png',
 '0',
 '612491873091_284.png',
 '1',
 '207998127593_3248.png',
 '0',
 '668120264286_278.png',
 '1',
 '744306592463_299.png',
 '0',
 '379555453762_64.png',
 '1',
 '950465767867_1787.png',
 '1',
 '987270537640_15.png',
 '0',
 '254659183021_1243.png',
 '1',
 '572780943183_7.png',
 '0',
 '989301179886_126.png',
 '0',
 '830006002974_104.png',
 '0',
 '274833361680_194.png',
 '0',
 '764696884251_56.png',
 '0',
 '279175507830_173.png',
 '0',
 '778608133606_3.png',
 '0',
 '129310496531_1624.png',
 '0',
 '48365

In [38]:
lab1 = [image[i] for i in range(len(image)) if i % 2 != 0]
img1 = [image[i] for i in range(len(image)) if i % 2 == 0]

In [39]:
len(lab1)

3016

In [40]:
image2 = df['Image1'].to_list()
image2

['441965561693_1725.png',
 '1',
 '578184120957_719.png',
 '1',
 '379555453762_57.png',
 '1',
 '936067480890_1806.png',
 '0',
 '228727013494_3335.png',
 '0',
 '389712748656_3311.png',
 '0',
 '532817958124_2491.png',
 '1',
 '858235946428_2693.png',
 '0',
 '701192330238_24.png',
 '0',
 '594143428478_288.png',
 '1',
 '482469995080_437.png',
 '0',
 '723791120719_2033.png',
 '0',
 '251404070836_988.png',
 '1',
 '609859592068_4.png',
 '0',
 '20173997_63.png',
 '1',
 '667615805298_3159.png',
 '0',
 '795591049648_269.png',
 '1',
 '272436316261_1940.png',
 '0',
 '208384063534_124.png',
 '0',
 '272365977423_3056.png',
 '1',
 '710898793562_2388.png',
 '1',
 '611532182871_1937.png',
 '1',
 '837265040191_2423.png',
 '0',
 '843777652566_9.png',
 '0',
 '333597054971_626.png',
 '1',
 '203648378218_12.png',
 '0',
 '791124267528_68.png',
 '1',
 '954618460788_831.png',
 '0',
 '483141243470_325.png',
 '0',
 '464599977359_2752.png',
 '1',
 '275661138762_1150.png',
 '0',
 '425886974239_2740.png',
 '0',
 '560

In [42]:
lab2 = [image2[i] for i in range(len(image2)) if i % 2 != 0]
img2 = [image2[i] for i in range(len(image2)) if i % 2 == 0]

In [44]:
len(lab2)

3016

In [48]:
final_df = pd.DataFrame(img1,columns=['Image'])
final_df

Image
0     833758612558_1846.png
1      357251708376_311.png
2     278611994141_2601.png
3      985714726449_129.png
4     222887373246_1773.png
...                     ...
3011   663772022816_157.png
3012   839263398699_744.png
3013    817481477091_20.png
3014  253890261988_3426.png
3015  988222288102_2994.png

[3016 rows x 1 columns]

In [49]:
final_df.insert(1,'labels',lab1)

In [50]:
final_df

Image labels
0     833758612558_1846.png      1
1      357251708376_311.png      1
2     278611994141_2601.png      0
3      985714726449_129.png      1
4     222887373246_1773.png      1
...                     ...    ...
3011   663772022816_157.png      1
3012   839263398699_744.png      1
3013    817481477091_20.png      0
3014  253890261988_3426.png      1
3015  988222288102_2994.png      0

[3016 rows x 2 columns]

In [51]:
final_df1 = pd.DataFrame(img2,columns=['Image'])
final_df1

Image
0     441965561693_1725.png
1      578184120957_719.png
2       379555453762_57.png
3     936067480890_1806.png
4     228727013494_3335.png
...                     ...
3011  161125882564_1817.png
3012   762364345542_645.png
3013  648426818801_2872.png
3014    753932316264_69.png
3015                    NaN

[3016 rows x 1 columns]

In [52]:
final_df1.insert(1,'labels',lab2)

In [53]:
final_df1

Image labels
0     441965561693_1725.png      1
1      578184120957_719.png      1
2       379555453762_57.png      1
3     936067480890_1806.png      0
4     228727013494_3335.png      0
...                     ...    ...
3011  161125882564_1817.png      0
3012   762364345542_645.png      1
3013  648426818801_2872.png      1
3014    753932316264_69.png      0
3015                    NaN    NaN

[3016 rows x 2 columns]

In [60]:
final_df = final_df.append(final_df1, ignore_index=True)

In [61]:
final_df['labels'].value_counts()

0    3025
1    3006
Name: labels, dtype: int64

In [63]:
final_df

Image labels
0     833758612558_1846.png      1
1      357251708376_311.png      1
2     278611994141_2601.png      0
3      985714726449_129.png      1
4     222887373246_1773.png      1
...                     ...    ...
6027  161125882564_1817.png      0
6028   762364345542_645.png      1
6029  648426818801_2872.png      1
6030    753932316264_69.png      0
6031                    NaN    NaN

[6032 rows x 2 columns]

In [62]:
final_df.to_csv("Final.csv")

In [68]:
bad = final_df[final_df['labels']=="1"]

In [72]:
bad_list = bad['Image'].to_list()
good_list = good['Image'].to_list()

In [75]:
good

Image labels
2     278611994141_2601.png      0
6     214189042515_3281.png      0
12     554448876390_107.png      0
13    674347030286_2524.png      0
14     796282255349_381.png      0
...                     ...    ...
6020  453251923703_2970.png      0
6024     339935510253_1.png      0
6025     241075064687_1.png      0
6027  161125882564_1817.png      0
6030    753932316264_69.png      0

[3025 rows x 2 columns]

In [67]:
good = final_df[final_df['labels']=="0"]

In [69]:
good.to_csv("Good_Quality.csv")

In [70]:
bad.to_csv("Bad_Quality.csv")

In [71]:
source_path = '/Volumes/My Book/Total_Dataset/OP'
good_folder = '/Volumes/My Book/Good'
bad_folder = '/Volumes/My Book/Bad'

In [73]:
import shutil, os
for f in good_list:
    shutil.copy(os.path.join(source_path,f),good_folder)

In [1]:
from sklearn.preprocessing import Normalizer
X = [[4, 1, 2, 2],
   [1, 3, 9, 3],
   
        [5, 7, 5, 1]]

In [9]:
import numpy as np
X = np.arange(10).reshape((5, 2))
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
import sklearn
normalizer = sklearn.preprocessing.Normalizer()

In [14]:
normalized_all_X = normalizer.transform(X)

In [15]:
sum_of_squares = np.square(normalized_all_X).sum(1)

In [17]:
sum_of_squares

array([1., 1., 1., 1., 1.])

In [18]:
normalized_all_X

array([[0.        , 1.        ],
       [0.5547002 , 0.83205029],
       [0.62469505, 0.78086881],
       [0.65079137, 0.7592566 ],
       [0.66436384, 0.74740932]])